### ISSUE TITLE
Do not sort Arrays

### ISSUE THREAD

**Issue by cocker-cc** [smortex/yaml-sort#2]
Do not sort Arrays, as Element-Order may be important.

**Comment by smortex** [comment]
The keyword here is _may_…

I wonder if we should be able to turn array sorting on/off using a flag or at an array level with some kind of control comments.  Any though?

**Comment by cocker-cc** [comment]
Arrays have a defined Order, and only the YAML's Author knows of this Order's Importance. For Example a List of IP-Addresses, or the Elements of a Search-Path.  Therefore the Order of Elements must be immutable.  

For me the whole Point of sorting the YAML is to prevent Endusers to accidentally insert duplicate Hash-Keys.

**Comment by smortex** [comment]
Thanks!

I just released 2.0.0 which should fix this.
